---
# tasks file for destroy_vch

- name : Delete Virtual Container Host
  command : {{ vchBinaryPath }}/{{ binary }} delete --target {{ vcenter_host }}  --user {{ vcenter_user }} --password {{ vcenter_password }} --thumbprint {{ vcenter_sslthumbprint }} --name {{ vch_name }}
  delegate_to : localhost
