---
# tasks file for destroy_vch

- name : Delete Virtual Container Host
  command : {{ vic_home }}/{{ vic_binary }} delete --target {{ vcenter_host }}  --user {{ vcenter_user }} --password {{ vcenter_password }} --thumbprint {{ vcenter_sslthumbprint }} --name {{ inventory_hostname }}
  delegate_to : localhost
