---
- hosts: localhost
  vars:
    vcenter_ovftool: /usr/bin/ovftool
    vcenter_host: 192.168.4.10
    vcenter_user: administrator@vsphere.local
    vcenter_password: VMware1!
    vcenter_datastore: vsanDatastore
    vcenter_cluster: Hackathon-Cluster
    vcenter_datacenter: Hackathon-Datacenter
    vic_name: team-4-vic
    mgmt_ip: 192.168.4.51
    vic_netmask: 255.255.255.0
    network_fqdn: 192.168.4.51
    dns_server: 8.8.8.8
    dns_searchpath: team4.local
    gateway: 192.168.4.254
    appliance_root: "VMware1!"
    permit_root_login: true
    ip_protocol: ipv4
    vic_home: /tmp/vic-tools
    registry_admin_password: VMware1!
    registry_port: 443
    registry_notary_port: 4443
    registry_db_password: VMware1!
    management_portal_port: 8282
    fileserver_port: 9443
    ova_path: /home/team4
    ova_file_name: vic-v1.1.1_56a309fb.ova
    
  roles:
  - deploy_vic

