- name: Deploy OVA Image on vCenter
  delegate_to: localhost
  command: >
    {{ vcenter_ovftool }}
    --acceptAllEulas
    --noSSLVerify
    --powerOn
    --machineOutput
    -dm=thin
    -ds={{ vcenter_datastore }}
    -n={{ vic_name }}
    --prop:"appliance.root_pwd={{appliance_root}}"
    --prop:"appliance.permit_root_login={{permit_root_login}}"
    --prop:"IpAssignment.IpProtocol={{ip_protocol}}"
    --prop:"network.fqdn={{network_fqdn}}"
    --prop:"network.ip0={{mgmt_ip}}"
    --prop:"network.gateway={{gateway}}"
    --prop:"network.netmask0={{vic_netmask}}"
    --prop:"network.DNS={{dns_server}}"
    --prop:"network.searchpath={{dns_searchpath}}"
    {% if registry_deploy is defined %}
    --prop:"registry.deploy={{registry_deploy}}"
    {% endif %}
    {% if registery_port is defined %}
    --prop:"registry.port={{registry_port}}"
    {% endif %}
    {% if registry_notary_port is defined %}
    --prop:"registry.notary_port={{registry_notary_port}}"
    {% endif %}
    {% if registry_admin_password is defined %}
    --prop:"registry.admin_password={{registry_admin_password}}"
    {% endif %}
    {% if registry_db_password is defined %}
    --prop:"registry.db_password={{registry_db_password}}"
    {% endif %}
    {% if registry_gc_enabled is defined %}
    --prop:"registry.gc_enabled={{registry_gc_enabled}}"
    {% endif %}
    {% if egistry_ssl_cert is defined %}
    --prop:"registry.ssl_cert={{registry_ssl_cert}}"
    {% endif %}
    {% if registry_ssl_cert_key is defined %}
    --prop:"registry.ssl_cert_key={{registry_ssl_cert_key}}"
    {% endif %}
    {% if management_portal_deploy is defined %}
    --prop:"management_portal.deploy={{management_portal_deploy}}"
    {% endif %}
    {% if management_portal_port is defined %}
    --prop:"management_portal.port={{management_portal_port}}"
    {% endif %}
    {% if management_portal_ssl_cert is defined %}
    --prop:"management_portal.ssl_cert={{management_portal_ssl_cert}}"
    {% endif %}
    {% if management_portal_ssl_cert_key is defined %}
    --prop:"management_portal.ssl_cert_key={{management_portal_ssl_cert_key}}"
    {% endif %}
    {% if fileserver_port is defined %}
    --prop:"fileserver.port={{fileserver_port}}"
    {% endif %}
    {% if fileserver_ssl_cert is defined %}
    --prop:"fileserver.ssl_cert={{fileserver_ssl_cert}}"
    {% endif %}
    {% if fileserver_ssl_cert_key is defined %}
    --prop:"fileserver.ssl_cert_key={{fileserver_ssl_cert_key}}"
    {% endif %}
    {% if networkmapping_network is defined %}
    --prop:"NetworkMapping.Network={{networkmapping_network}}"
    {% endif %}
    "{{ ova_path }}/{{ ova_file_name }}"
    vi://'{{ vcenter_user | urlencode }}':'{{ vcenter_password | urlencode }}'@{{ vcenter_host }}/{{ vcenter_datacenter }}/host/{{ vcenter_cluster }} 

