---
# tasks file for deploy_vch

- name : Check VCH deploy binary
  stat :
    path : {{ vic_home }}/{{ vic_binary }}
  register : binaryFile
  delegate_to : localhost
- name : Verify Binary File
  assert : binaryFile.exists
- name : Deploy Virtual Container Host on vSphere
  command : {{ vic_home }}/{{ vic_binary }} create --name={{ vch_name }} --target={{ vcenter_host }} --thumbprint={{ vcenter_sslthumbprint }} --user={{ vcenter_user }} --password={{ vcenter_password }} --compute-resource={{ vcenter_cluster }} --public-network={{ vch_network }} --bridge-network={{ vch_network }} --no-tls
  delegate_to : localhost
